# to update to the latest channel do
#  `./update-to-nixpkgs.sh nixos-20.03`
let
  bootStrap = import <nixpkgs> {};
  rev = "7cb76200088f45cd24a9aa67fd2f9657943d78a4";
  # hash generated by doing nix-prefetch-url --unpack https://github.com/NixOS/nixpkgs/archive/{rev}.tar.gz
  hash = "12q3jy364nrcixfnd522jc9piagnc16p5b5l57mgp01lk311k7z1";
  src = builtins.fetchTarball
    {
      name = "nixpkgs-tarball-${rev}";
      url = "https://github.com/NixOS/nixpkgs/archive/${rev}.tar.gz";
      sha256 = hash;
    };
in
bootStrap.runCommand "nixpkgs-${rev}" {
  outputHashMode = "recursive";
  outputHashAlgo = "sha256";
  outputHash = hash;
  inherit src;
}
  ''
    cp -r $src $out
  ''
